import { Link } from 'react-router-dom'
import { Check } from 'lucide-react'
import { api } from '../../lib/api'
import { useApi } from '../../lib/useApi'
import { p2pkAddress } from '../../lib/ergo'
import { num } from '../../lib/format'
import { Async, Callout, Card, Field, Hash } from '../../components/ui'

// Autolykos v2 table size N(h): 2^26, then +5% every 51,200 blocks from height 614,400,
// frozen from height 4,198,400 (reference node: AutolykosPowScheme.calcN).
const N_BASE = 2 ** 26
const N_INCREASE_START = 614_400
const N_INCREASE_PERIOD = 51_200
const N_FREEZE_HEIGHT = 4_198_400
const V2_ACTIVATION = 417_792
const K = 32

function calcN(h) {
  if (h < N_INCREASE_START) return N_BASE
  if (h >= N_FREEZE_HEIGHT) return 2_143_944_600
  const iterations = Math.floor((h - N_INCREASE_START) / N_INCREASE_PERIOD) + 1
  let n = N_BASE
  for (let i = 0; i < iterations; i++) n = Math.floor(n / 100) * 105
  return n
}

const G_HEX = '0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798'

function LivePow() {
  const state = useApi(() => api.latestBlocks(1), [])
  return (
    <Async state={state}>
      {(blocks) => {
        const b = blocks?.[0]
        if (!b?.pow) return <p>Couldn&apos;t fetch the PoW solution.</p>
        let pkAddr = null
        try {
          pkAddr = p2pkAddress(b.pow.pk)
        } catch {
          pkAddr = null
        }
        const N = calcN(b.height)
        return (
          <Card className="not-prose my-6 p-2 sm:p-4">
            <div className="px-2 pb-2 text-xs font-semibold tracking-wide text-stone-500 uppercase">
              PoW solution of block <Link to={`/block/${b.height}`} className="text-ergo-600 hover:underline dark:text-ergo-400">#{num(b.height)}</Link>
            </div>
            <Field name="pk" value={<Hash value={b.pow.pk} full />}>
              The miner&apos;s public key. It corresponds to{' '}
              {pkAddr ? (
                <>
                  the address <Hash value={pkAddr} to={`/address/${pkAddr}`} />
                  {pkAddr === b.minerAddress && (
                    <span className="ml-1 inline-flex items-center gap-1 font-semibold text-emerald-600">
                      <Check className="size-3.5" /> matches the reward address
                    </span>
                  )}
                </>
              ) : (
                'the reward address'
              )}
              . The block reward can only be unlocked with this key.
            </Field>
            <Field name="w" value={<Hash value={b.pow.w} full />}>
              {b.pow.w === G_HEX ? 'This is exactly the secp256k1 generator point G — ' : ''}
              a fixed value in Autolykos v2, kept only so the header format stays the same.
            </Field>
            <Field name="n (nonce)" value={<span className="font-mono">{b.pow.n}</span>}>
              8 bytes the miner keeps changing until it finds a small enough hash. This is the only part that is actually “mined”.
            </Field>
            <Field name="d" value={<span className="font-mono">{String(b.pow.d)}</span>}>
              Always 0 in v2 (in v1, d was part of the solution).
            </Field>
            <Field name="N at this height" value={<span className="font-mono">{num(N)}</span>}>
              The number of elements in the table a miner must keep in memory. N × 32 bytes ≈ {(N * 32 / 2 ** 30).toFixed(1)} GiB (a theoretical figure — mining
              software may lay the table out a little differently).
            </Field>
          </Card>
        )
      }}
    </Async>
  )
}

export default function Autolykos() {
  return (
    <>
      <p>
        Like Bitcoin, Ergo uses <strong>Proof-of-Work</strong>: to add a block, a miner has to find a number (a nonce) that makes the hash of the header smaller
        than a threshold called the <Link to="/learn/difficulty">target</Link>. The difference lies in the function being hashed. Bitcoin uses double SHA-256 —
        extremely fast, and therefore dominated by specialized ASIC machines. Ergo uses <strong>Autolykos</strong>, a <em>memory-hard</em> algorithm: mining
        speed is limited by memory bandwidth, something ordinary GPUs are already very good at.
      </p>

      <h2 id="y-tuong">The idea: the k-sum problem</h2>
      <p>
        Picture a giant lookup table that only fits in a graphics card&apos;s memory. Each mining attempt is “pick 32 random cells from the table, add them
        up, hash the sum, and check whether you got lucky”. The hard part is not the maths — it is fetching 32 cells from a multi-gigabyte table, billions of
        times.
      </p>
      <p>Autolykos is based on the k-sum problem: pick k elements from a large list so that their sum satisfies some condition. Concretely, in v2, with k = {K}:</p>
      <ol>
        <li>
          There is a <strong>table</strong> of N elements, each generated by hashing its index together with the block height. The miner precomputes the whole
          table for the current height and keeps it in the GPU&apos;s VRAM.
        </li>
        <li>
          For each nonce tried, hash (header message ‖ nonce) to derive <strong>{K} pseudo-random indexes</strong> into the table.
        </li>
        <li>
          Fetch the {K} elements at those indexes, <strong>add them up</strong>, then hash the sum with <code>blake2b256</code>.
        </li>
        <li>
          If the result (read as an integer) is below the target → block found. Otherwise → change the nonce and try again.
        </li>
      </ol>
      <pre>
        <code>{`for nonce in 0, 1, 2, ...:
    idx[0..31] = genIndexes(hash(msg ‖ nonce), N)
    s = table[idx[0]] + table[idx[1]] + ... + table[idx[31]]
    if blake2b256(s) < target:
        return nonce   // 🎉 new block`}</code>
      </pre>
      <p>
        Every attempt needs {K} random reads from a table that is gigabytes in size. Recomputing table elements each time instead of storing them is far slower,
        so whoever has the most memory bandwidth mines fastest. An ASIC that wants to compete also has to carry a large amount of fast memory — at which point it
        has essentially become a GPU.
      </p>

      <h2 id="bang-n">An ever-growing table N</h2>
      <p>
        To keep commodity hardware competitive in the long run, the table size N grows over time: it starts at 2<sup>26</sup> (≈ 67 million elements), then from
        height {num(N_INCREASE_START)} it grows by 5% every {num(N_INCREASE_PERIOD)} blocks (~71 days), and stops growing around height {num(N_FREEZE_HEIGHT)}.
      </p>
      <table>
        <thead>
          <tr>
            <th>Height</th>
            <th>N</th>
            <th>≈ N × 32 bytes</th>
          </tr>
        </thead>
        <tbody>
          {[500_000, 1_000_000, 1_500_000, 2_000_000, 3_000_000].map((h) => (
            <tr key={h}>
              <td className="tabular-nums">{num(h)}</td>
              <td className="font-mono tabular-nums">{num(calcN(h))}</td>
              <td className="tabular-nums">{((calcN(h) * 32) / 2 ** 30).toFixed(1)} GiB</td>
            </tr>
          ))}
        </tbody>
      </table>

      <h2 id="v1-v2">Autolykos v1 and v2</h2>
      <p>
        The first version (v1, used since mainnet launched in 2019) was designed to be <strong>non-outsourceable</strong>: a solution was tied to the miner&apos;s
        secret key, to make pool mining risky — if a pool handed out work, a miner could simply keep the reward. In practice this didn&apos;t stop pools (they used
        smart contracts to split rewards); it only made everything more complicated.
      </p>
      <p>
        The hard fork at block <strong>{num(V2_ACTIVATION)}</strong> (February 2021) introduced <strong>Autolykos v2</strong>: it dropped non-outsourceability so that
        mining pools work normally, and introduced the growing-N mechanism described above. The header format still keeps the four fields{' '}
        <code>pk, w, n, d</code>, but:
      </p>
      <ul>
        <li>
          <code>pk</code> is still the public key of the miner (or pool) — whoever receives the reward.
        </li>
        <li>
          <code>w</code> is always the secp256k1 generator point <em>G</em> (<code>0279be667e…</code>) — a placeholder constant.
        </li>
        <li>
          <code>d</code> is always 0.
        </li>
        <li>
          <code>n</code> — the 8-byte nonce — is the only part that actually carries information about the solution.
        </li>
      </ul>

      <h2 id="block-that">On a real block</h2>
      <p>Here is the solution of the latest block, fetched live from mainnet:</p>
      <LivePow />
      <Callout type="tip" title="Cheap to verify, expensive to find">
        Finding a nonce takes tens of trillions of attempts across the whole network (at ~0.5 TH/s, about 60 trillion per 2-minute block). But to check it, a node only needs to recompute {K} table elements at{' '}
        {K} indexes — it doesn&apos;t need the whole table. That&apos;s why a node running on an ordinary computer can still validate every block.
      </Callout>

      <h2 id="xem-them">See also</h2>
      <ul>
        <li>
          <Link to="/learn/difficulty">Difficulty &amp; nBits</Link> — how the target is computed and adjusted.
        </li>
        <li>
          <Link to="/learn/emission">Emission schedule</Link> — how much ERG a miner earns per block.
        </li>
        <li>
          <Link to="/learn/block">Blocks &amp; headers</Link> — where the PoW solution sits in the header.
        </li>
      </ul>
    </>
  )
}
